import type { Doctor } from "./types"

export const specialties = [
  "Cardiology",
  "Dermatology",
  "Neurology",
  "Orthopedics",
  "Pediatrics",
  "Psychiatry",
  "Ophthalmology",
  "Gynecology",
]

export const doctors: Doctor[] = [
  {
    id: "doctor-1",
    name: "Sarah Johnson",
    photo: "https://media.istockphoto.com/id/1371998919/photo/cropped-portrait-of-an-attractive-young-female-doctor-giving-thumbs-up-while-working-in-her.jpg?s=612x612&w=0&k=20&c=5oPD2p5gc7ZQjgyjPAJui9eOGKF8sK_GG6MJpYXmA7s=",
    specialty: "Cardiology",
    rating: 4.8,
    location: "Downtown Medical Center",
    availableSlots: [
      { day: "Monday", time: "9:00 AM" },
      { day: "Monday", time: "11:30 AM" },
      { day: "Wednesday", time: "2:00 PM" },
      { day: "Friday", time: "10:00 AM" },
    ],
  },
  {
    id: "doctor-2",
    name: "Michael Chen",
    photo: "https://t4.ftcdn.net/jpg/02/60/04/09/360_F_260040900_oO6YW1sHTnKxby4GcjCvtypUCWjnQRg5.jpg",
    specialty: "Dermatology",
    rating: 4.9,
    location: "Westside Health Clinic",
    availableSlots: [
      { day: "Tuesday", time: "8:30 AM" },
      { day: "Tuesday", time: "1:00 PM" },
      { day: "Thursday", time: "3:30 PM" },
    ],
  },
  {
    id: "doctor-3",
    name: "Emily Rodriguez",
    photo: "https://img.freepik.com/free-photo/woman-doctor-wearing-lab-coat-with-stethoscope-isolated_1303-29791.jpg?semt=ais_hybrid&w=740",
    specialty: "Pediatrics",
    rating: 4.7,
    location: "Children's Medical Center",
    availableSlots: [
      { day: "Monday", time: "10:00 AM" },
      { day: "Wednesday", time: "9:30 AM" },
      { day: "Wednesday", time: "2:30 PM" },
      { day: "Friday", time: "11:00 AM" },
    ],
  },
  {
    id: "doctor-4",
    name: "David Wilson",
    photo: "/placeholder.svg?height=400&width=400",
    specialty: "Orthopedics",
    rating: 4.6,
    location: "Sports Medicine Clinic",
    availableSlots: [
      { day: "Tuesday", time: "11:00 AM" },
      { day: "Thursday", time: "9:00 AM" },
      { day: "Thursday", time: "4:00 PM" },
    ],
  },
  {
    id: "doctor-5",
    name: "Olivia Thompson",
    photo: "/placeholder.svg?height=400&width=400",
    specialty: "Neurology",
    rating: 4.9,
    location: "Neuroscience Institute",
    availableSlots: [
      { day: "Monday", time: "2:00 PM" },
      { day: "Wednesday", time: "10:30 AM" },
      { day: "Friday", time: "1:30 PM" },
    ],
  },
  {
    id: "doctor-6",
    name: "James Parker",
    photo: "/placeholder.svg?height=400&width=400",
    specialty: "Psychiatry",
    rating: 4.7,
    location: "Behavioral Health Center",
    availableSlots: [
      { day: "Tuesday", time: "9:30 AM" },
      { day: "Tuesday", time: "3:00 PM" },
      { day: "Thursday", time: "1:00 PM" },
    ],
  },
  {
    id: "doctor-7",
    name: "Sophia Lee",
    photo: "/placeholder.svg?height=400&width=400",
    specialty: "Ophthalmology",
    rating: 4.8,
    location: "Vision Care Center",
    availableSlots: [
      { day: "Monday", time: "8:30 AM" },
      { day: "Wednesday", time: "1:00 PM" },
      { day: "Friday", time: "9:00 AM" },
    ],
  },
  {
    id: "doctor-8",
    name: "Robert Martinez",
    photo: "/placeholder.svg?height=400&width=400",
    specialty: "Gynecology",
    rating: 4.6,
    location: "Women's Health Clinic",
    availableSlots: [
      { day: "Tuesday", time: "10:00 AM" },
      { day: "Thursday", time: "2:30 PM" },
      { day: "Thursday", time: "4:30 PM" },
    ],
  },
  {
    id: "doctor-9",
    name: "Jennifer Adams",
    photo: "/placeholder.svg?height=400&width=400",
    specialty: "Cardiology",
    rating: 4.5,
    location: "Heart & Vascular Institute",
    availableSlots: [],
  },
]
